version: '3.1'

services:
  biserver:
    image: andrespp/biserver
    command: ["start"]
    restart: always
    volumes:
    - ./data/biserver-data:/biserver-ce/tomcat/webapps
    ports:
      - "80:8080"
